### ISSUE TITLE
Error reading both temp and humidity

### ISSUE THREAD

**Issue by sldghmmr** [dhrubasaha08/DHT11#4]
I was playing around with a DHT11 and a ESP8266 NodeMCU ESP-12E and could not get both temp and humidity to display.  I ran the script with just temp and just humidity, and they worked fine.  After much consternation, I eliminated the error by putting a delay(500) between each reading.  I did not try any shorter delays.  Here is what my sketch looked like:

#include <DHT11.h>

// Create an instance of the DHT11 class and set the digital I/O pin.
DHT11 dht11(2);

void setup() {
  // Initialize serial communication at 115200 baud.
  Serial.begin(115200);
}

void loop() {
  // Read the temperature from the sensor.
  float temperature = dht11.readTemperature();

  delay(500);                                                   // Required to get both readings consecutively

  // Read the humidity from the sensor.
  float humidity = dht11.readHumidity();

  // If the temperature and humidity readings were successful, print them to the serial monitor.
  if (temperature != -1 && humidity != -1) {
    Serial.print("Temperature: ");
    Serial.print(temperature);
    Serial.println(" C");

    Serial.print("Humidity: ");
    Serial.print(humidity);
    Serial.println(" %");
  } else {
    // If the temperature or humidity reading failed, print an error message.
    Serial.println("Error reading data");
  }

  // Wait for .5 seconds before the next reading.
  delay(500);
}

**Comment by dhrubasaha08** [comment]
Hello @sldghmmr,

Thank you for sharing your issue with the DHT11 and ESP8266 NodeMCU ESP-12E. It's interesting that adding a delay(500) between readings resolved the problem with displaying both temperature and humidity. Since the code works flawlessly on the Arduino Uno, the timing differences on the ESP8266 platform might be the root cause.

I don't have an ESP8266 based board, but I'll test the code on the ESP32 Dev Module to gain insights into its compatibility and try to fix the issue. Your feedback is valuable, and I appreciate your dedication to improving the library's functionality.

Best regards,
@dhrubasaha08

**Comment by dhrubasaha08** [comment]
@sldghmmr! I tried the [**example** - ReadTempAndHumidity](https://github.com/dhrubasaha08/DHT11/blob/main/examples/ReadTempAndHumidity/ReadTempAndHumidity.ino) on my ESP32 Dev Board, and it works perfectly with pin 4. After rechecking your code, I believe the issue might have been due to the NodeMCU ESP8266 ESP-12E board's pin 2, which is an ADC pin. This could have caused the error when attempting to use it for the DHT11 sensor. I suggest you check the example again by using pin 4 on your board.

**Comment by sldghmmr** [comment]
I appreciate your following up on this issue.  Here are my findings:  I ran the original code I sent you as I have since started programing on VS Code using PlatformIO, as opposed to Arduino IDE.  It's growing on me.  Anyway, using my original code on the Arduino IDE, I was able to reproduce the errors, so I switched to GPIO 14 (GPIO4 is being used by my I2C LCD display).  I had the exact same results on that pin.  Messing around with the delay, I started receiving humidity data with somewhere between 300 and 400 milliseconds delay.  Below that produced no humidity data.
      Furthermore, since I was switching to PlatformIO, I ended up using the Adafruit DHT library with the Adafruit Unified Sensor library and no delay was necessary at all.  I also feel like the results were more granular.  No offense.  It looks like the only library of yours that showed up in VS Code was your SimpleUltrasonic library.  Thanks again
________________________________
