### ISSUE TITLE
Enhancement: Enable fetching of both humidity and temperature at the same time

### ISSUE THREAD

**Issue by DrJPK** [dhrubasaha08/DHT11#9]
Loving the simplicity of this library.  However, as the DHT11 is quite slugish and doesn't like to be polled faster than 1Hz, if you try and call readTemperature() and then readHumidity() too close together the second call returns 253.

Might this be corrected if the constructor had 2 variables say _T and _H, and a new method readSensor() was added? readSensor() contains the current content of readHumidity function but instead of returning data[0] it sets _H = data[0] and _T = data[2]

readTemperature() then becomes

readTemperature(){
 return _T;
} 

or similar.  Would this work with the way you have designed this library? or would it break something you have planned?

**Comment by dhrubasaha08** [comment]
@DrJPK You're absolutely right, it will make the sensor faster and it's not going to break anything else in the code. By creating a new private method "readSensors()" it can be done!

Thanks for pointing this out. I'd highly suggest you create a fork, then make a new branch (base = dev, name it something like 'optimization-core-lib' or 'enhancement-core-lib') off the dev branch and implement your idea. Otherwise, I'll implement this change later when I do it in the v2.1.0 update."
